config {
  type: "view",
  schema: "staging",
  description: "Staged and formatted meeting events"
}

SELECT
  uri AS event_uri,
  event_type_uri,
  name AS event_name,
  status AS event_status,
  start_time AS start_timestamp,
  end_time AS end_timestamp,
  TIMESTAMP_DIFF(end_time, start_time, MINUTE) AS duration_minutes,
  invitees_active,
  invitees_limit,
  location_type,
  location,
  canceled_by,
  canceler_type,
  cancel_reason,
  created_at AS created_timestamp,
  updated_at AS updated_timestamp
FROM
  ${ref("event")}
WHERE
  COALESCE(_fivetran_deleted, FALSE) IS FALSE